-- =====================================
-- MAGNITUDE
-- =====================================
-- Find total customers by countries
SELECT
country,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?
SELECT
gdp.category,
SUM(gfs.sales_amount) total_revenue
FROM gold.fact_sales gfs
LEFT JOIN gold.dim_products gdp
ON gdp.product_key = gfs.product_key
GROUP BY gdp.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT
gdc.customer_key,
gdc.first_name,
gdc.last_name,
SUM(gfs.sales_amount) total_revenue
FROM gold.fact_sales gfs
LEFT JOIN gold.dim_customers gdc
ON gdc.customer_key = gfs.customer_key
GROUP BY
gdc.customer_key,
gdc.first_name,
gdc.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold item across countries?
SELECT
gdc.country,
SUM(gfs.quantity) total_quantity
FROM gold.fact_sales gfs
LEFT JOIN gold.dim_customers gdc
ON gdc.customer_key = gfs.customer_key
GROUP BY gdc.country
ORDER BY total_quantity DESC
